[package]
name = "valentinus"
version = "0.1.2"
edition = "2021"
authors = ["Nigel Christian <nigel.christian@hiahatf.org>"]
documentation = "https://docs.rs/valentinus"
description = "Proof-of-concept vector db built with LMDB bindings"
repository = "https://github.com/kn0sys/valentinus"
license = "Apache-2.0"
readme = "README.md"
build = "build.rs"
keywords = [
    "nlp",
    "deep-learning",
    "machine-learning",
    "transformers",
    "vector-database"
]

[lib]
name = "valentinus"
path = "src/lib.rs"
crate-type = ["lib"]

[features]
doc-only = ["rust-bert/doc-only"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode        = "1.3.3"
env_logger     = "0.10.0"
lazy_static    = "1.4.0"
linfa-nn       = "0.7.0"
lmdb-rs        = "0.7.6"
log            = "0.4"
ndarray        = "0.15.6"
ndarray-rand   = "0.14.0"
regex          = "1.10.5"
rust-bert      = "0.22.0"
serde          = { version = "1.0", features = ["derive"] }
sysinfo        = "0.30.13" 
uuid           = "1.10.0"

[dev-dependencies]
rand           = "0.8.5"

[package.metadata.docs.rs]
features = ["doc-only"]
