[package]
name = "valentinus"
version = "0.1.1"
edition = "2021"
authors = ["Nigel Christian <nigel.christian@hiahatf.org>"]
description = "Proof-of-concept vector db built with LMDB bindings"
repository = "https://github.com/kn0sys/valentinus"
license = "Apache-2.0"
readme = "README.md"
keywords = [
    "nlp",
    "deep-learning",
    "machine-learning",
    "transformers",
    "vector-database"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger     = "0.10.0"
linfa-nn       = "0.7.0"
lmdb-rs        = "0.7.6"
log            = "0.4"
ndarray        = "0.15.6"
ndarray-rand   = "0.14.0"
regex          = "1.10.5"
rust-bert      = "0.22.0"
serde_json     = "1.0.120"
serde          = { version = "1.0", features = ["derive"] } 
uuid           = "1.10.0"
