name: build

on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        mkdir all-Mini-LM-L6-v2_onnx
        wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/onnx/model.onnx
        mv model.onnx all-Mini-LM-L6-v2_onnx/
        wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/tokenizer.json
        mv tokenizer.json all-Mini-LM-L6-v2_onnx/
    - name: build and test
      run: |
        cargo build && RUST_TEST_THREADS=1 cargo test
