name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcpu.zip
        unzip libtorch-cxx11-abi-shared-with-deps-2.1.1+cpu.zip
    - name: Build
      run: |
        export LIBTORCH=$GITHUB_WORKSPACE/libtorch
        export LD_LIBRARY_PATH=$LIBTORCH/lib
        export LIBTORCH_BYPASS_VERSION_CHECK=1
        cargo build
    - name: Run tests
      run: cargo test
