name: test

on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main", "stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        rustup update
        mkdir all-MiniLM-L6-v2_onnx
        cd all-MiniLM-L6-v2_onnx && wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/config.json
        wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/onnx/model.onnx
        wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/special_tokens_map.json
        wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/tokenizer_config.json
        wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/tokenizer.json
        wget https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/main/vocab.txt
    - name: test
      run: RUST_TEST_THREADS=1 cargo test
